### ISSUE TITLE
How do you Enable Press 

### ISSUE THREAD

**Issue by zacharyshupp** [JustinGrote/Press#12]
I am very interested in your structure, I would like to test it out but I don't see any instructions on how to configure press.

**Comment by JustinGrote** [comment]
It is still pretty early in development and docs are not available yet, however you can look at other repositories for it being used. You can also use the commands individually rather than the Invoke-Build task structure:
https://github.com/JustinGrote/SecretManagement.KeePass/
https://github.com/JustinGrote/Mortar

**Comment by zacharyshupp** [comment]
Thank you, I will look through both of those.
